<?xml version="1.0"?>
<package format="3">
  <name>fork_control</name>
  <version>1.4.0</version>
  <description>Independent GPIO fork controller with command and state topics.</description>
  <maintainer email="robotics@example.com">sesac</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>python3-gpiozero</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
