version: 1
topics:
  - id: odom
    enabled: true
    source: /odom
    target: /{robot}/odom
    type: nav_msgs/msg/Odometry
    worker_rate: {}
    qos:
      reliability: best_effort
      durability: volatile
      history: keep_last
      depth: 5

  - id: tf
    enabled: true
    source: /tf
    target: /{robot}/tf
    type: tf2_msgs/msg/TFMessage
    worker_rate: {}
    qos:
      reliability: best_effort
      durability: volatile
      history: keep_last
      depth: 20

  - id: tf_static
    enabled: true
    source: /tf_static
    target: /{robot}/tf_static
    type: tf2_msgs/msg/TFMessage
    worker_rate: {}
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 1

  - id: amcl_pose
    enabled: true
    source: /amcl_pose
    target: /{robot}/amcl_pose
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    worker_rate: {}
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 10

  - id: battery
    enabled: false
    source: /ros_robot_controller/battery
    target: /{robot}/battery
    type: sensor_msgs/msg/BatteryState
    worker_rate:
      max_rate_hz: 0.2
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 1

  - id: diagnostics
    enabled: true
    source: /diagnostics
    target: /{robot}/diagnostics
    type: diagnostic_msgs/msg/DiagnosticArray
    worker_rate: {}
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 10

  - id: scan
    enabled: false
    source: /scan_filtered
    target: /{robot}/scan_filtered
    type: sensor_msgs/msg/LaserScan
    worker_rate:
      max_rate_hz: 2.0
    qos:
      reliability: best_effort
      durability: volatile
      history: keep_last
      depth: 1
