#!/usr/bin/env bash
set -euo pipefail

DEST="."
DOMAIN="Project knowledge base"
FORCE=false

usage() {
  cat <<'USAGE'
Usage: init-llm-wiki.sh [options]

Initialize a new llm-wiki-core project.

Options:
  --dest PATH          Project root. Default: .
  --domain DOMAIN      Wiki domain. Default: Project knowledge base
  --force              Overwrite existing files.
  -h, --help           Show help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dest)
      DEST="${2:?--dest requires PATH}"
      shift 2
      ;;
    --domain)
      DOMAIN="${2:?--domain requires DOMAIN}"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_LLM_WIKI="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST="$(mkdir -p "$DEST" && cd "$DEST" && pwd)"

copy_dir_contents() {
  local src="$1"
  local target="$2"
  local src_real
  local target_real

  mkdir -p "$target"
  src_real="$(cd "$src" && pwd -P)"
  target_real="$(cd "$target" && pwd -P)"

  if [ "$src_real" = "$target_real" ]; then
    return 0
  fi

  local entries=("$src_real"/*)
  if [ ! -e "${entries[0]}" ]; then
    return 0
  fi

  cp -r "${entries[@]}" "$target_real/"
}

# Copy core Python package
copy_dir_contents "$SRC_LLM_WIKI/llm_wiki_core" "$DEST/llm-wiki-core/llm_wiki_core"

# Copy core-owned runtime assets
copy_dir_contents "$SRC_LLM_WIKI/scripts" "$DEST/llm-wiki-core/scripts"
copy_dir_contents "$SRC_LLM_WIKI/hooks" "$DEST/llm-wiki-core/hooks"
copy_dir_contents "$SRC_LLM_WIKI/templates" "$DEST/llm-wiki-core/templates"
copy_dir_contents "$SRC_LLM_WIKI/agent-os" "$DEST/llm-wiki-core/agent-os"
copy_dir_contents "$SRC_LLM_WIKI/tests" "$DEST/llm-wiki-core/tests"

# Create standard directories
mkdir -p \
  "$DEST/llm-wiki/concepts" \
  "$DEST/llm-wiki/decisions" \
  "$DEST/llm-wiki/comparisons" \
  "$DEST/llm-wiki/queries" \
  "$DEST/llm-wiki/sources" \
  "$DEST/llm-wiki/metadata" \
  "$DEST/llm-wiki/raw"

# Helper for writing files
write_file() {
  local path="$1"
  local content="$2"
  if [ -e "$path" ] && [ "$FORCE" != "true" ]; then
    return 0
  fi
  echo "$content" > "$path"
}

# Write SCHEMA.md
write_file "$DEST/llm-wiki/SCHEMA.md" "# Wiki Schema

## Domain
$DOMAIN

## Core Rules
- This wiki is local-owned mutable source unless bound as a published artifact elsewhere.
- Team/Project published artifacts are consumed as read-only snapshots, not edited in place.
- Every compiled page should include frontmatter with title, created, updated, type, status, tags, and sources when applicable.
- Every durable page should be listed in index.md.
- Every ingest, query filing, schema change, or promotion event should append to log.md.
- Raw sources are immutable-by-default: no silent overwrite, deletion, or untracked mutation.

## Base Folders
- raw/: captured source material and evidence inputs.
- concepts/: reusable concepts and explanations.
- decisions/: accepted decisions and ADR-style records.
- comparisons/: side-by-side analyses.
- queries/: filed query results worth preserving.
- sources/: source summaries or source registry-oriented pages.
- metadata/: state, events, registries, and derived metadata."

# Write project-owned wiki_stack.yaml
write_file "$DEST/wiki_stack.yaml" "wiki_artifacts: []
personal_wikis: []

selection_policy:
  default_mode: active-work
  conflict_resolution:
    default_action: ask_user
    record_user_decision: true
    autonomous_allowed: false
  priority_rules:
    priority_source: yaml_order
    earlier_entry_has_higher_priority: true
    group_block_has_equal_priority: true
    priority_grants_canonical_authority: false

mutable_source_wiki_policy:
  source_binding_order:
    - source_binding_id: local-promotion-shelf
    - source_binding_id: local-mutable-wiki"

# Write index.md
write_file "$DEST/llm-wiki/index.md" "# Wiki Index

> Content catalog. Every durable wiki page should be listed here.
> Last updated: $(date +%Y-%m-%d) | Total pages: 0

## Concepts

## Decisions

## Comparisons

## Queries

## Sources"

# Write log.md
write_file "$DEST/llm-wiki/log.md" "# Wiki Log

> Chronological record of wiki actions. Append-only.
> Format: ## [YYYY-MM-DD] action | subject

## [$(date +%Y-%m-%d)] create | Wiki scaffold initialized
- Domain: $DOMAIN
- Generated by: llm-wiki-core/scripts/init-llm-wiki.sh"
